name       : libmicrohttpd
version    : 0.9.58
release    : 6
source     :
    - https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.58.tar.gz : 7a11e1376c62ff95bd6d2dfe6799d57ac7cdbcb32f70bfbd5e47c71f373e01f3
license    : LGPL-2.1
component  : network.web
summary    : GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application.
description: |
    GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application.
builddeps  :
    - pkgconfig(libcurl) # extended checks
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
