name       : libmicrohttpd
version    : 0.9.42
release    : 4
source     :
    - http://ftpmirror.gnu.org/libmicrohttpd/libmicrohttpd-0.9.42.tar.gz : 00352073367003da40607319e4090a6a8308748b59246ae80e9871f34dad7d5b
license    : LGPL-2.1
summary    : GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application.
description: |
    GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
