name       : libmicrohttpd
version    : 0.9.77
release    : 9
source     :
    - https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.77.tar.gz : 9e7023a151120060d2806a6ea4c13ca9933ece4eacfc5c9464d20edddb76b0a0
homepage   : https://www.gnu.org/software/libmicrohttpd/
license    : LGPL-2.1-or-later
component  : network.web
summary    : GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application
description: |
    GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application.
builddeps  :
    - pkgconfig(libcurl) # extended checks
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/info
check      : |
    %make check
